import Head from "next/head";
import { useState, useEffect } from "react";
import Rating from "../components/rating";
import Submit from "../components/submit";

export default function Home() {
  const [score, setScore] = useState(0);
  const [submit, setSubmit] = useState(false);
  return (
    <div className="px-8 mt-32">
      <Head>
        <title>Tailwind App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/icons/sunny_cloud.ico" />
      </Head>
      <main>
        {submit ? (
          <Submit score={score}/>
        ) : (
          <Rating onClick={setScore} onSubmit={setSubmit} />
        )}
      </main>
    </div>
  );
}
